import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";

const font = Roboto_Slab({
  subsets: ["vietnamese"],
  weight: ["100", "200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Pursuit",
    default: "Home | Pursuit",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${font.className}`}>
          <Header />
          <Toaster />
          <main>{children}</main>
        </body>
      </SessionProvider>
    </html>
  );
}
